<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="spot_leg" params="leg_name" >

        <xacro:if value="${leg_name == 'fl'}">
            <xacro:property name="base_to_hip_xyz"            value="${base_to_hip_x} ${base_to_hip_y} 0" />
            <xacro:property name="hip_to_upper_leg_xyz"       value="0 ${hip_to_upper_leg_y} 0" />
            <xacro:property name="leg_name_long"    value="front_left" />
        </xacro:if>
        <xacro:if value="${leg_name == 'fr'}">
            <xacro:property name="base_to_hip_xyz"            value="${base_to_hip_x} -${base_to_hip_y} 0" />
            <xacro:property name="hip_to_upper_leg_xyz"       value="0 -${hip_to_upper_leg_y} 0" />
            <xacro:property name="leg_name_long"    value="front_right" />
        </xacro:if>
        <xacro:if value="${leg_name == 'hl'}">
            <xacro:property name="base_to_hip_xyz"            value="-${base_to_hip_x} ${base_to_hip_y} 0" />
            <xacro:property name="hip_to_upper_leg_xyz"       value="0 ${hip_to_upper_leg_y} 0" />
            <xacro:property name="leg_name_long"    value="rear_left" />
        </xacro:if>
        <xacro:if value="${leg_name == 'hr'}">
            <xacro:property name="base_to_hip_xyz"            value="-${base_to_hip_x} -${base_to_hip_y} 0" />
            <xacro:property name="hip_to_upper_leg_xyz"       value="0 -${hip_to_upper_leg_y} 0" />
            <xacro:property name="leg_name_long"    value="rear_right" />
        </xacro:if>

        <xacro:property name="hip_x_joint" value="${leg_name}.hx"/>
        <xacro:property name="hip_y_joint" value="${leg_name}.hy"/>
        <xacro:property name="knee_joint" value="${leg_name}.kn"/>

        <link name="${leg_name_long}_hip">
            <visual>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name_long}_hip.dae" />
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name}_hip_collision.stl" />
                    <cylinder radius="${hip_width}" length="${hip_length}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${hip_mass}"/>
                <inertia ixx="${(1/12) * hip_mass * (hip_width * hip_width + hip_height * hip_height)}" ixy="0.0" ixz="0.0"
                            iyy="${(1/12) * hip_mass * (hip_length * hip_length + hip_height * hip_height)}" iyz="0.0"
                            izz="${(1/12) * hip_mass * (hip_length * hip_length + hip_width * hip_width)}" />     
            </inertial>
        </link>
        <gazebo reference="${leg_name_long}_hip">
            <kp>400000.0</kp>
            <kd>1.0</kd>
            <mu1>0.8</mu1>
            <mu2>0.8</mu2>
            <maxVel>0.0</maxVel>
            <minDepth>0.002</minDepth>
        </gazebo>
        <joint name="${hip_x_joint}" type="revolute">
            <origin xyz="${base_to_hip_xyz}" rpy="0 0 0" />
            <axis xyz="1 0 0" />
            <parent link="body" />
            <child link="${leg_name_long}_hip" />
            <limit effort="1e6" velocity="1e6" lower="-3.0" upper="3.0" />
        </joint>
        <link name="${leg_name_long}_upper_leg">
            <visual>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name_long}_upper_leg.dae" />
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${-0.25*upper_leg_height}"/>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name}_upper_leg_collision.stl" />
                    <cylinder radius="${0.6*upper_leg_width}" length="${0.8*upper_leg_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 -0.14" rpy="0 0 0" />
                <mass value="${upper_leg_mass}"/>
                <inertia ixx="${(1/12) * upper_leg_mass * (upper_leg_width * upper_leg_width + upper_leg_height * upper_leg_height)}" ixy="0.0" ixz="0.0"
                            iyy="${(1/12) * upper_leg_mass * (upper_leg_length * upper_leg_length + upper_leg_height * upper_leg_height)}" iyz="0.0"
                            izz="${(1/12) * upper_leg_mass * (upper_leg_length * upper_leg_length + upper_leg_width * upper_leg_width)}" />     
            </inertial>
        </link>
        <gazebo reference="${leg_name_long}_upper_leg">
            <kp>400000.0</kp>
            <kd>1.0</kd>
            <mu1>0.8</mu1>
            <mu2>0.8</mu2>
            <maxVel>0.0</maxVel>
            <minDepth>0.002</minDepth>
        </gazebo>
        <joint name="${hip_y_joint}" type="revolute">
            <origin xyz="${hip_to_upper_leg_xyz}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <parent link="${leg_name_long}_hip" />
            <child link="${leg_name_long}_upper_leg" />
            <limit effort="1e6" velocity="1e6" lower="-3.0" upper="3.0" />
        </joint>
        <link name="${leg_name_long}_lower_leg">
            <visual>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name_long}_lower_leg.dae" />
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${-0.35*lower_leg_height}"/>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name_long}_lower_leg_collision.stl" scale="0.82 0.97 0.98"/>
                    <cylinder radius="${lower_leg_length}" length="${0.6*lower_leg_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 -0.16" rpy="0 0 0" />
                <mass value="${lower_leg_mass}"/>
                <inertia ixx="${(1/12) * lower_leg_mass * (lower_leg_width * lower_leg_width + lower_leg_height * lower_leg_height)}" ixy="0.0" ixz="0.0"
                            iyy="${(1/12) * lower_leg_mass * (lower_leg_length * lower_leg_length + lower_leg_height * lower_leg_height)}" iyz="0.0"
                            izz="${(1/12) * lower_leg_mass * (lower_leg_length * lower_leg_length + lower_leg_width * lower_leg_width)}" />     
            </inertial>
        </link>
        <gazebo reference="${leg_name_long}_lower_leg">
            <kp>400000.0</kp>
            <kd>1.0</kd>
            <mu1>0.8</mu1>
            <mu2>0.8</mu2>
            <maxVel>0.0</maxVel>
            <minDepth>0.002</minDepth>
        </gazebo>
        <joint name="${knee_joint}" type="revolute">
            <origin xyz="${upper_leg_to_lower_leg_x} 0 -${upper_leg_to_lower_leg_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <parent link="${leg_name_long}_upper_leg" />
            <child link="${leg_name_long}_lower_leg" />
            <limit effort="1e6" velocity="1e6" lower="-3.0" upper="3.0" />
        </joint>
        <link name="${leg_name_long}_ee">
            <collision name="${leg_name_long}_ee_collision">
                <origin rpy="0 0 0" xyz="0 0 ${lower_leg_length}"/>
                <geometry>
                    <mesh filename="package://spot_description/meshes/${leg_name_long}_lower_leg_collision.stl" scale="0.82 0.97 0.98"/>
                    <sphere radius="${lower_leg_length}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${leg_name_long}_foot" type="fixed">
            <parent link="${leg_name_long}_lower_leg" />
            <child link="${leg_name_long}_ee" />
            <origin xyz="0 0 -${lower_leg_to_foot_z}" rpy="0 0 0" />
        </joint>
        <gazebo reference="${leg_name_long}_ee">
            <kp>400000.0</kp>
            <kd>1.0</kd>
            <mu1>0.8</mu1>
            <mu2>0.8</mu2>
            <maxVel>0.0</maxVel>
            <minDepth>0.002</minDepth>
        </gazebo>

    </xacro:macro>
</robot>